export const ROSCO = [
  { letter: "A", clue: "Trastorno del espectro que tiene el perro de Maru", answer: "Autismo" },
  { letter: "B", clue: "Instrumento que toca Gime", answer: "Bajo" },
  { letter: "C", clue: "Lugar donde se conocieron Luciana y Jessica", answer: "CBC" },
  { letter: "D", clue: "Contiene D. Comida por la que es famosa Maru", answer: "Asado" },
  { letter: "E", clue: "Contiene E. Artículo que colecciona Ton y de los que tiene miles", answer: "Perfumes" },
  { letter: "F", clue: "El ex más nombrado", answer: "Fede Lama" },
  { letter: "G", clue: "Único varón del grupo", answer: "Gastón" },
  { letter: "H", clue: "Contiene H. Nacionalidad de Bea", answer: "Chilena" },
  { letter: "I", clue: "Colegio al que iba la conocida banda almeja", answer: "ISIL" },
  { letter: "J", clue: "Contiene J. Banda a la que recientemente fueron a ver Gime y Marian", answer: "Los Piojos" },
  { letter: "K", clue: "Contiene K. Tribu urbana a la que pertenecían Lu, Gime y Maru", answer: "Punk" },
  { letter: "L", clue: "Contiene L. Famoso boliche de Zona Oeste de colectora", answer: "Coolsite" },
  { letter: "M", clue: "Nombre con el que se conoce popularmente a la casa en la que estamos", answer: "Miami" },
  { letter: "N", clue: "Nombre de pila del padre de Gime apodado Beto", answer: "Norberto" },
  { letter: "O", clue: "Característica de las tías que conforman el grupo de whatsapp", answer: "Opositoras" },
  { letter: "P", clue: "Deporte que intentamos imponer y no pasó", answer: "Padel" },
  { letter: "Q", clue: "Contiene Q. Carrera en la que se conocieron Gime y Marian", answer: "Arquitectura" },
  { letter: "R", clue: "Tribu urbana a la que pertenecía Luciana", answer: "Rolinga" },
  { letter: "S", clue: "Apellido de conocida actriz apodada La Nefasta", answer: "Suárez" },
  { letter: "T", clue: "Apodo de todas como grupo", answer: "Tias" },
  { letter: "U", clue: "Contiene U. Primera eliminada del grupo de tías Pinamar", answer: "Gusa" },
  { letter: "V", clue: "Deporte que juega actualmente Marianela", answer: "Voley" },
  { letter: "W", clue: "Famosa canción de la banda de Manchester que van a ver en Noviembre", answer: "Wonderwall" },
  { letter: "X", clue: "Contiene X. Canción de Wisin y Yandel de 2005 “Hoy es noche de...”", answer: "Sexo" },
  { letter: "Y", clue: "Contiene Y: Banda que van a ver Gime y Lu en Septiembre", answer: "Green Day" },
  { letter: "Z", clue: "Contiene Z: Localidad en la que vive Luciana, answer: "Ituzaingo" },
   ];
